### ISSUE TITLE
Data Science Cheatsheets are not available 

### ISSUE THREAD

**Issue by 360macky** [DataScienceResearchPeru/OpenSource-RoadMap-DataScience#11]
En [OpenSource-RoadMap-DataScience/hojas-apuntes](https://github.com/DataScienceResearchPeru/OpenSource-RoadMap-DataScience/tree/master/hojas-apuntes)

Las imágenes de hojas de apuntes o cheatsheets no se visualizan, debido a que el repositorio al que enlazan `datasciencescoop/Data-Science--Cheat-Sheet` ya no está disponible:

![Imágenes](https://user-images.githubusercontent.com/47821093/111912176-7cb47380-8a36-11eb-8a17-162b89aab3e6.png)
![Repositorio Data-Science--Cheat-Sheet](https://user-images.githubusercontent.com/47821093/111912179-80e09100-8a36-11eb-999b-238bcd07b083.png)

Del la tabla de contenidos:
![Tabla de contenidos](https://user-images.githubusercontent.com/47821093/111912363-3d3a5700-8a37-11eb-877a-710244e014af.png)
Todos los enlaces también apuntan al repositorio, `datasciencescoop/Data-Science--Cheat-Sheet`, excepto por **Artificial Intelligence** y **Big Data** (que sí están disponibles).

**Comment by pablodz** [comment]
Merged

**Comment by 360macky** [comment]
Thanks @pablodz! 🎆
