### ISSUE TITLE
Sobre las fuentes

### ISSUE THREAD

**Issue by bregydoc** [DataScienceResearchPeru/OpenSource-RoadMap-DataScience#2]
Hola, me parece muy buena iniciativa; sin embargo, este repositorio se parece demasiado al ya bastante conocido de OSSU (Open Source Society University): [data-science](https://github.com/ossu/data-science). Creo que deberían de informar de las fuentes y reconocer el trabajo de otros autores.

Saludos

**Comment by Cuica20** [comment]
Gracias, estaba mapeado este cambio.
